### PR TITLE
Added support for UTF8 encoding 

### PR DESCRIPTION
**Pull request by savamura**
Hi Artem, I've created a pull request to add UTF8 support as the most widespread encoding nowadays. Not sure how to add proper tests to the solution, but tested locally.
Used "🚀" rocket as an example of 4-byte UTF8 char.
Used code samples:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint
http://stackoverflow.com/questions/15181809/javascript-charcodeat0-stuck-at-55357
https://gist.github.com/volodymyr-mykhailyk/2923227

Additional info: https://en.wikipedia.org/wiki/UTF-8

### CODE REVIEW

**Comment by vibornoff** [comment]
Hi! Many thanks for your participation.

I've  reviewed your pull request and there are some issues.

As [jsperf.com has been broken](https://github.com/jsperf/jsperf.com/issues/18#issuecomment-113569132) I have to create [a small benchmark at jsfiddle](http://jsfiddle.net/vibornoff/kct18qn8/1/).

I slightly modifed your `string_to_utf8bytes` to achieve at about x4 speedup and its performance becomes competitive w/ original `string_to_bytes`. So I'm considering to replace original `string_to_bytes` with UTF-8 capable one.

Unfortunately I'm out of spare time for now.
I'll let your pull request in ASAP.

**Comment by savamura** [comment]
Wow, it looks like function inlining makes the code much faster, which is obvious, but I didn't take the efficiency into consideration, which is a shame. :) Let me fix it then.

**Comment by savamura** [comment]
Following your lead I've got rid of redundant function calls in the second method as well and managed to boost its performance too! Check this out https://jsfiddle.net/kct18qn8/3/
I've updated the pull request with the tweaks.

**Comment by vibornoff** [comment]
Hmm...
```javascript
String.fromCharCode.apply( String, strBuffer.subarray(0, j) );
```
[Bad idea](http://stackoverflow.com/questions/22747068/is-there-a-max-number-of-arguments-javascript-functions-can-accept).

Guys from Google Closure already shoot their leg once and the [solution](https://github.com/google/closure-library/commit/da353e0265ea32583ea1db9e7520dce5cceb6f6a#diff-13b3e2af02e1e9ddff26b515a7bf46afL52) seems well to me.

**Comment by savamura** [comment]
Ok, I'll break it into chunks. I wonder where did they take their magic number (8192) from...

**Comment by savamura** [comment]
I just couldn't resist the temptation to make batch size a little bigger :)

**Pull request merged**
